/*
Group - 41
Praneet Karna - 2020A7PS1202P
Kshitij Tandon - 2020A7PS0972P
Devashish Siwatch - 2020A7PS0113P
Samyak Jain - 2020A7PS0089P
Chaitanya Iyer - 2020A7PS0012P
*/

#include <stdio.h>
#include "lexer.h"

char *enum_to_token_name_string[] = {
    "ID",
    "NUM",
    "RNUM",
    "AND",
    "OR",
    "TRUE",
    "FALSE",
    "PLUS",
    "MINUS",
    "MUL",
    "DIV",
    "LT",
    "LE",
    "GT",
    "GE",
    "EQ",
    "NE",
    "DEF",
    "ENDDEF",
    "DRIVERDEF",
    "DRIVERENDDEF",
    "COLON",
    "RANGEOP",
    "SEMICOL",
    "COMMA",
    "ASSIGNOP",
    "SQBO",
    "SQBC",
    "BO",
    "BC",
    "INTEGER",
    "REAL",
    "BOOLEAN",
    "OF",
    "ARRAY",
    "START",
    "END",
    "DECLARE",
    "MODULE",
    "DRIVER",
    "PROGRAM",
    "GET_VALUE",
    "PRINT",
    "USE",
    "WITH",
    "PARAMETERS",
    "TAKES",
    "INPUT",
    "RETURNS",
    "FOR",
    "IN",
    "SWITCH",
    "CASE",
    "BREAK",
    "DEFAULT",
    "WHILE"
    // "COMMENTMARK"
};

// saving all the tokens generated by the lexer in a file
void save_all_tokens(FILE *input_file, FILE *output_file)
{
    initialize_lexer_variables(input_file);
    Token token;
    while (1)
    {
        token = get_next_token(input_file);
        printf("\n%s\t%d\t%s\n", enum_to_token_name_string[token.token_name], token.line_no, token.id.str);
        if (token.token_name == EOF)
        {
            break;
        }
        fprintf(output_file, "%s\t\t%d\t\t%s\n", enum_to_token_name_string[token.token_name], token.line_no, token.id.str);
        // break;
    }
}

// driver code
// int main()
// {
//     FILE *input_file, *token_output_file;
//     char ch;

//     // Open the input file in read mode
//     input_file = fopen("input.txt", "r");

//     // If the file doesn't exist or can't be opened, exit the program
//     if (input_file == NULL)
//     {
//         printf("Unable to open file");
//         return 1;
//     }
//     printf("File opened successfully\n");

//     // open the file to save the tokens generated by the lexer
//     token_output_file = fopen("token_output.txt", "w");
//     // If the file doesn't exist or can't be opened, exit the program
//     if (token_output_file == NULL)
//     {
//         printf("Unable to open file");
//         return 1;
//     }
//     printf("Token output File opened successfully\n");

//     // printf("%c", get_next_char(input_file));
//     // printf("%c", get_next_char(input_file));

//     // save all the tokens generated by the lexer in a file
//     save_all_tokens(input_file, token_output_file);

//     // Close the file
//     fclose(input_file);

//     fclose(token_output_file);

//     return 0;
// }
